import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Slimmii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="fixed top-0 w-full">
        <nav className="flex flex-row items-center justify-start flex-wrap gap-8 p-4 bg-blue-900 bg-opacity-90">
          <img src="slimmii.png" className="w-24"></img>
        </nav>
      </header>

      <div className="bg-fixed h-screen w-screen top-0 bg-cover bg-no-repeat bg-center" style={{backgroundImage: 'url("./background_top.png")'}}></div>


      <footer>
        
      </footer>
    </div>
  )
}

export default Home
